[theme]

primaryColor="#24DE84"
backgroundColor="#1D1B1A"
secondaryBackgroundColor="#333333"
textColor="#fafafa"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false

[client]
toolbarMode = "auto"
showErrorDetails = true
showSidebarNavigation = false

[ui]
hideTopBar = true  
disableClickToZoom = true