[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
showSidebarNavigation = false

[ui]
hideTopBar = true  
disableClickToZoom = true