# .streamlit/secrets.toml para Streamlit Cloud

# Variable de entorno principal
# ENVIRONMENT = "production"

# URL de base de datos directa
DATABASE_URL = "postgresql://postgres.wlvckhnnugvghhisprmk:ballersappcuervacho@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"

# Configuración de Google
[google]
type = "service_account"
project_id = "ballers-app"
private_key_id = "e795f782d6470acce19a09416057628987d7f739"
# IMPORTANTE: La private_key debe tener \n literales, no saltos de línea reales
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDiDf0ZEZdRZ8Mr\nbZsLH2fnFxb43oYXYHD2zxqjavzohF7YCdSOfRkpIOGR9ohRCfQu03aj0+9jy1cM\nhA0B+AzW6pSWPhcKu9oKzH1I1tN+cCPBHUIw6+S0ujSKcSiRsh+2fy+SPgLVuORM\nohIzNu8txqoAtT/bkK7W9HdDRaSgJtya5wT7daXLrxTTc+TJCwitq6IZ8CmHZ8QJ\nBX0yJ6KwPlEbr8FFkkiODMuqLpQKDptsU88Eqc4VUfLDsJZEwUXtWc7J2j9DJUEK\numVh9Xityw6NKVZH03bRhSSkv3YpkAbJni63UlLDXdkc/PySbZXTEeb1bYhJEM2v\nGTsmj7idAgMBAAECggEAJ2FaeziGTOcvp+wjO2/QMQDjvp09bOsfIs/3iwqDXppY\nz3f+8Ie4j2KsCTqSitOaF2I9Y9Ly/EabNpH2liY5TmN1WSsd5n/NP15aYQsTsw4k\nHGtVcaJWqGlb59ZIxADs52UGy4pEAimAlB0T4JosVqQqT49DvaNZ4haahDyorkFi\n+QiV5PzKUehjV2vpJ1/zkAuYKMVeUfslNOGNYdzzY6Hq93f8dG7s7FFBiA7AetmQ\nI5KXlZajKmoBdy5jWc/7SkjThTyMo2xXNcRVKnfFitxg2BMc9FfJ3/LFZFrYmsXH\nVT9HMK0bWHxdTsfhrrI0j+W1XyATwjjimPkdkxMoQQKBgQD8eTB7nwJsRQjb+pJs\nwVGEPrTOE8Z06IbhjgDyh7a7XbScXyHp1pXDvcCXTW9Sjrs2U222pCdsw2pJQy/C\nEwhAuUO8zh90kSS0ph8eQjyEoZZUm2pKjaOtFvcUeSMPdCjWquS281IHuMcaE1Ov\n0XTOkBtqFT6c3kIK7pMFu+VlsQKBgQDlNlRTpVp2kT1HOXMdJQGhUGBHERfmXmca\nT/51joRtmVHK8uKlWq9xqMMuy1/Vy1+0ibDnsXkDUqQa7ymddLbdjd017O3Z4Eh3\nW6uO50kyxbA2/E7ugBKiNBJN/KcHzUZQXQBE2D3/+rKZkO7pc/9GcNsmA45l5933\npn94NaoArQKBgQDc4UnBXYPJJTxy9+1SqG6gvBuCj1p4vVYDzzCU/panpXt1suUA\np3OvJDtyI5TZLXYsOSErQMIdLXm3TshhijUWKv9QFyT93l22jf97gYdgod3bd3yu\nbOxdalIP30sFIiL4a9pdFNMXXlkSPwZgM2d1sC3LyXpV0z0EQ2TtB03SgQKBgF7k\niyzF/BmyL2hZRGsAcxhRqkpBrV9WHeEq1PHeOr0VCGO5AlPqo0+uyn+I+vgL5mdb\nyb1iH/NcN0xfTx88vqginz5ABIh67gVcEj5rSkaWyUk6U4MxyoUUga9/tbbpKP8E\nQaQ+0gwzwdUJx58mwrxq5I9sUXum7qIkcAlYTjVRAoGAUy0NwfjN0tenF1wBg/HF\n8zpSgmAxFfuF3L31NqtA8bLcruvG9slsNZMbCoiWoCLKL3eJ2y5bk+dG5tEaU1qf\n9XR16tSSdm8uu2RakCNaX/GsbKyNsMz8H5aAWb9n32qz634YUlKgtMyBaYAPWLvY\nYtAhPoJmb5g5kt3NJW08aXo=\n-----END PRIVATE KEY-----"
client_email = "ballers-service@ballers-app.iam.gserviceaccount.com"
client_id = "107756172253846955711"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ballers-service%40ballers-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# IDs de producción
calendar_id = "info@ballersbangkok.com"
accounting_sheet_id = "1Lf1lpplLOrewG4V-8949Ny9PLg6nX5n9_GgIWtQWqQY"

# Configuración de la app
[app]
session_secret = "ballers-app-production-2025-secure-key-Q4FAATxa4mw9sZk"